-- Temizlenmis gunluk ve haftalik CSV dosyalarinin PostgreSQL tablolari.
-- CSV aktarimi bir sonraki adimda yapilacak.

-- Her ulkenin gunluk vaka, olum, test, asilama ve demografik gostergelerini tutar.
CREATE TABLE IF NOT EXISTS covid.countries_clean (
    iso_code TEXT,
    continent TEXT,
    location TEXT NOT NULL,
    date DATE NOT NULL,
    total_cases DOUBLE PRECISION,
    new_cases DOUBLE PRECISION,
    new_cases_smoothed DOUBLE PRECISION,
    total_deaths DOUBLE PRECISION,
    new_deaths DOUBLE PRECISION,
    new_deaths_smoothed DOUBLE PRECISION,
    total_cases_per_million DOUBLE PRECISION,
    new_cases_per_million DOUBLE PRECISION,
    new_cases_smoothed_per_million DOUBLE PRECISION,
    total_deaths_per_million DOUBLE PRECISION,
    new_deaths_per_million DOUBLE PRECISION,
    new_deaths_smoothed_per_million DOUBLE PRECISION,
    reproduction_rate DOUBLE PRECISION,
    icu_patients DOUBLE PRECISION,
    icu_patients_per_million DOUBLE PRECISION,
    hosp_patients DOUBLE PRECISION,
    hosp_patients_per_million DOUBLE PRECISION,
    weekly_icu_admissions DOUBLE PRECISION,
    weekly_icu_admissions_per_million DOUBLE PRECISION,
    weekly_hosp_admissions DOUBLE PRECISION,
    weekly_hosp_admissions_per_million DOUBLE PRECISION,
    total_tests DOUBLE PRECISION,
    new_tests DOUBLE PRECISION,
    total_tests_per_thousand DOUBLE PRECISION,
    new_tests_per_thousand DOUBLE PRECISION,
    new_tests_smoothed DOUBLE PRECISION,
    new_tests_smoothed_per_thousand DOUBLE PRECISION,
    positive_rate DOUBLE PRECISION,
    tests_per_case DOUBLE PRECISION,
    tests_units TEXT,
    total_vaccinations DOUBLE PRECISION,
    people_vaccinated DOUBLE PRECISION,
    people_fully_vaccinated DOUBLE PRECISION,
    total_boosters DOUBLE PRECISION,
    new_vaccinations DOUBLE PRECISION,
    new_vaccinations_smoothed DOUBLE PRECISION,
    total_vaccinations_per_hundred DOUBLE PRECISION,
    people_vaccinated_per_hundred DOUBLE PRECISION,
    people_fully_vaccinated_per_hundred DOUBLE PRECISION,
    total_boosters_per_hundred DOUBLE PRECISION,
    new_vaccinations_smoothed_per_million DOUBLE PRECISION,
    new_people_vaccinated_smoothed DOUBLE PRECISION,
    new_people_vaccinated_smoothed_per_hundred DOUBLE PRECISION,
    stringency_index DOUBLE PRECISION,
    population_density DOUBLE PRECISION,
    median_age DOUBLE PRECISION,
    aged_65_older DOUBLE PRECISION,
    aged_70_older DOUBLE PRECISION,
    gdp_per_capita DOUBLE PRECISION,
    extreme_poverty DOUBLE PRECISION,
    cardiovasc_death_rate DOUBLE PRECISION,
    diabetes_prevalence DOUBLE PRECISION,
    female_smokers DOUBLE PRECISION,
    male_smokers DOUBLE PRECISION,
    handwashing_facilities DOUBLE PRECISION,
    hospital_beds_per_thousand DOUBLE PRECISION,
    life_expectancy DOUBLE PRECISION,
    human_development_index DOUBLE PRECISION,
    population BIGINT,
    excess_mortality_cumulative_absolute DOUBLE PRECISION,
    excess_mortality_cumulative DOUBLE PRECISION,
    excess_mortality DOUBLE PRECISION,
    excess_mortality_cumulative_per_million DOUBLE PRECISION,
    PRIMARY KEY (location, date)
);

-- Python analizinde hazirlanan haftalik vaka ozetlerini tutar.
CREATE TABLE IF NOT EXISTS covid.weekly_cases (
    location TEXT NOT NULL,
    hafta_baslangici DATE NOT NULL,
    mevcut_vaka_toplami DOUBLE PRECISION,
    kayitli_gun INTEGER,
    dolu_gun INTEGER,
    eksik_gun INTEGER,
    tam_hafta BOOLEAN,
    raporlama_araligi_disi BOOLEAN,
    raporlama_sinir_haftasi BOOLEAN,
    onceki_hafta_tarihi DATE,
    onceki_hafta_vaka DOUBLE PRECISION,
    onceki_hafta_tam BOOLEAN,
    hafta_araligi INTEGER,
    haftalik_degisim DOUBLE PRECISION,
    haftalik_degisim_yuzde DOUBLE PRECISION,
    population BIGINT,
    haftalik_vaka_milyon_basina DOUBLE PRECISION,
    hafta_sonu DATE,
    hafta_sonu_toplam_vaka DOUBLE PRECISION,
    hafta_sonu_toplam_eksik BOOLEAN,
    haftalik_yeni_vaka DOUBLE PRECISION,
    veri_durumu TEXT,
    PRIMARY KEY (location, hafta_baslangici)
);

-- Python analizinde hazirlanan haftalik olum ozetlerini tutar.
CREATE TABLE IF NOT EXISTS covid.weekly_deaths (
    location TEXT NOT NULL,
    hafta_baslangici DATE NOT NULL,
    mevcut_olum_toplami DOUBLE PRECISION,
    kayitli_gun INTEGER,
    dolu_gun INTEGER,
    eksik_gun INTEGER,
    tam_hafta BOOLEAN,
    veri_durumu TEXT,
    onceki_hafta_tarihi DATE,
    onceki_hafta_olum DOUBLE PRECISION,
    onceki_hafta_tam BOOLEAN,
    hafta_araligi INTEGER,
    haftalik_olum_degisim DOUBLE PRECISION,
    haftalik_olum_degisim_yuzde DOUBLE PRECISION,
    population BIGINT,
    haftalik_olum_milyon_basina DOUBLE PRECISION,
    hafta_sonu DATE,
    hafta_sonu_toplam_olum DOUBLE PRECISION,
    hafta_sonu_toplam_olum_eksik BOOLEAN,
    mevcut_olum_milyon_basina DOUBLE PRECISION,
    haftalik_yeni_olum DOUBLE PRECISION,
    PRIMARY KEY (location, hafta_baslangici)
);

-- Python analizinde hazirlanan haftalik test ozetlerini tutar.
CREATE TABLE IF NOT EXISTS covid.weekly_tests (
    location TEXT NOT NULL,
    hafta_baslangici DATE NOT NULL,
    mevcut_test_toplami DOUBLE PRECISION,
    kayitli_gun INTEGER,
    dolu_gun INTEGER,
    eksik_gun INTEGER,
    tam_hafta BOOLEAN,
    haftalik_yeni_test DOUBLE PRECISION,
    veri_durumu TEXT,
    kismen_dolu_hafta BOOLEAN,
    veri_yok_hafta BOOLEAN,
    test_birimi TEXT,
    hafta_sonu DATE,
    PRIMARY KEY (location, hafta_baslangici)
);
-- Python analizinde her hafta icin son gecerli asi oranini tutar.
-- Asilamada yedi gunun tamamini istemiyoruz; haftadaki en guncel gecerli gozlem kullanilir.
CREATE TABLE IF NOT EXISTS covid.weekly_vaccinations (
    location TEXT NOT NULL,
    hafta_baslangici DATE NOT NULL,
    hafta_sonu DATE,
    gozlem_tarihi DATE,
    people_vaccinated_per_hundred DOUBLE PRECISION,
    people_fully_vaccinated_per_hundred DOUBLE PRECISION,
    gozlem_gecikmesi_gun INTEGER,
    veri_durumu TEXT,
    PRIMARY KEY (location, hafta_baslangici)
);
